import pygame

pygame.init()

N_ROWS = 12
N_COLS = 12
COUNT_MINES = 15

EMPTY = 16
MINE = 32
MASK_FLAG = 64
MASK_QUESTION = 128
CELL_SIZE = 50

PADDING_TOP = 70
PADDING = 10
BUTTON_PADDING = 10
FPS = 120

WIDTH = N_COLS * CELL_SIZE + 2 * PADDING
HEIGHT = N_ROWS * CELL_SIZE + PADDING + PADDING_TOP
BACK_COLOR = pygame.Color('#DDDDDD')
TEXT_COLOR = [
    None,
    '#100ECF',
    '#0590CF',
    '#079E78',
    '#239E06',
    '#B3A009',
    '#E8E016',
    '#E87110',
    '#E81212'
]
FONT_SIZE = int(CELL_SIZE * 0.7)
CELL_OUTSET_WIDTH = int(CELL_SIZE * 0.1)
LIGHT_COEFF = 30

# Окно сегмента
SEGMENT_TABLE_TOP_MARGIN = 10
SEGMENT_TABLE_LEFT_MARGIN = 50
SEGMENT_TABLE_RIGHT_MARGIN = 50
SEGMENT_TABLE_FONT_SIZE = 40
SEGMENT_TABLE_BORDER_WIDTH = 2
SEGMENT_TABLE_PADDING = 3
SEGMENT_TABLE_COLOR_BORDER = '#004d00'
SEGMENT_TABLE_COLOR_BACK = '#001a00'
SEGMENT_TABLE_COLOR_TEXT = '#00ff7f'
SEGMENT_TABLE_MIN_WIDTH_TEXT = 3
SEGMENT_TABLE_ANTIALIAS = False
SEGMENT_TABLE_FONT = pygame.font.Font('data/Segment7Standard.otf',
                                      SEGMENT_TABLE_FONT_SIZE)
# ФИКСИРОВАНИЕ ТАБЛО
SEGMENT_TABLE_ALIGING_LEGT = 1
SEGMENT_TABLE_ALIGING_RIGHT = 2
SEGMENT_TABLE_ALIGING_CENTER = 3